trigger: none

schedules:
- cron: "30 0-2 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: "true"

variables:
- group: huawei

jobs:

- job: build

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'

  - script: pip install -r requirements.txt
    displayName: 'Install requirements'

  - script: |
      python3 main.py --client huawei_iam --username $HUA2_USERNAME --password $PASSWORD --git $HUA2_GIT
    displayName: 'Run hua 5-9'
    env:
      PARENT_USER: atzouhua