schedules:
- cron: "10 0-2 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: "true"

jobs:

- job: build

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'

  - script: pip install -r requirements.txt
    displayName: 'Install requirements'

  - script: |
      python3 main.py --client huawei_iam --username $YUFEI2_USERNAME --password $PASSWORD --git $YUFEI2_GIT
    displayName: 'Run Iam5'