trigger: none

schedules:
- cron: "0 6-8 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: "true"

variables:
- group: huawei

jobs:

- job: build

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'

  - script: pip install -r requirements.txt
    displayName: 'Install requirements'

  - script: |
      python3 main.py --client huawei_iam --username $LEWEI7_USERNAME --password $PASSWORD --git $LEWEI7_GIT
    displayName: 'Run lewei 30-34'
    env:
      PARENT_USER: atlewei