trigger: none

schedules:
- cron: "30 3-5 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: "true"

variables:
- group: huawei

jobs:

- job: build

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'

  - script: pip install -r requirements.txt
    displayName: 'Install requirements'

  - script: |
      python3 main.py --client huawei --iam --username $MAYUN5_USERNAME --password $PASSWORD --git $MAYUN5_GIT
    displayName: 'Run mayun 20-24'
    env:
      PARENT_USER: atmayun