name: HuaWeiIamYuFei

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '50 0-2 * * *'

env:
  DING_TOKEN: ${{ secrets.DING_TOKEN }}
  REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
  PARENT_USER: caoyufei
  GIT_A: ${{ secrets.IAM_001_GIT }}
  GIT_B: ${{ secrets.IAM_002_GIT }}
  GIT_C: ${{ secrets.YUFEI003_GIT }}
  GIT_D: ${{ secrets.YUFEI004_GIT }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'

    - name: requirements
      run: |
        pip3 install -r requirements.txt

    - name: Run
      run: |
        python3 main.py --client huawei_iam --username ${{ secrets.YUFEI_USERNAME }} --password ${{ secrets.PASSWORD }} --git ${{ secrets.YUFEI_GIT }}
