name: IamYufei2

on:
  push:
    branches: [ dev ]
#  schedule:
#    - cron: '30 6-8 * * *'

env:
  DING_TOKEN: ${{ secrets.DING_TOKEN }}
  PARENT_USER: caoyufei

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'

    - name: requirements
      run: |
        pip3 install -r requirements.txt

    - name: Run
      run: |
        python3 main.py --client huawei_iam --username ${{ secrets.YUFEI2_USERNAME }} --password ${{ secrets.PASSWORD }} --git ${{ secrets.YUFEI2_GIT }}
