name: HuaWeiMadou

on:
#  push:
#    branches: [ master ]
  schedule:
    - cron: '58 0 * * *'

env:
  id_rsa: ${{ secrets.MAC_ID_RSA }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'

    - name: requirements
      run: |
        pip3 install -r requirements.txt

    - name: Run HUAWEI yufei
      run: |
        python3 main.py --client madou --username ${{ secrets.CAOYUFEI_USERNAME }} --password ${{ secrets.CAOYUFEI_PASSWORD }} --git-url ${{ secrets.CAOYUFEI_GIT }

    - name: Run HUAWEI hua
      run: |
        python3 main.py --client madou --username ${{ secrets.HUA_USERNAME }} --password ${{ secrets.HUA_PASSWORD }} --git-url ${{ secrets.HUA_GIT }